version: '3'

services:

  api:
    build: .
    ports:
      - '4321:4321'
    depends_on:
      - postgres
    env_file:
      - .env
    container_name: orkgnlp_api_container
    restart: on-failure
    networks:
      - orkgnlp_api

  postgres:
    image: "postgres:11-alpine"
    container_name: orkgnlp_postgres_container
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - 'postgres:/usr/share/postgresql/data'
    networks:
      - orkgnlp_api

networks:
  orkgnlp_api:

volumes:
  postgres:
    driver: local
