[tool.poetry]
name = "orkg-nlp-api"
version = "0.1.0"
description = "REST API to ORKG-NLP"
authors = ["Omar Arab Oghli <omar.araboghli@outlook.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7.1,<3.10"
fastapi = "~0.76.0"
gunicorn = "~20.1.0"
uvicorn = "~0.17.6"
<<<<<<< Updated upstream
orkgnlp = "^0.1.8"
=======
orkgnlp = "0.3.0"
>>>>>>> Stashed changes
pytest = "^7.1.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
